/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    borderRadius: {
      none: '0px',
      sm: '0px',
      DEFAULT: '0px',
      md: '0px',
      lg: '0px',
      xl: '0px',
      '2xl': '0px',
      '3xl': '0px',
      full: '9999px',
    },
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#b9ccb2',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#84967e',
        'outline-variant': '#3b4b37',
        'surface-tint': '#00e639',
        primary: '#ebffe2',
        'on-primary': '#003907',
        'primary-container': '#00ff41',
        'on-primary-container': '#007117',
        'inverse-primary': '#006e16',
        secondary: '#ffd393',
        'on-secondary': '#432c00',
        'secondary-container': '#fdaf00',
        'on-secondary-container': '#694600',
        tertiary: '#f9f9f9',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#dcdddd',
        'on-tertiary-container': '#5f6161',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#72ff70',
        'primary-fixed-dim': '#00e639',
        'on-primary-fixed': '#002203',
        'on-primary-fixed-variant': '#00530e',
        'secondary-fixed': '#ffddaf',
        'secondary-fixed-dim': '#ffba43',
        'on-secondary-fixed': '#281800',
        'on-secondary-fixed-variant': '#614000',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
      },
      fontFamily: {
        mono: ['"JetBrains Mono"', '"Courier New"', 'monospace'],
      },
      backgroundImage: {
        scanlines:
          'repeating-linear-gradient(0deg, rgba(0,230,57,0.1) 0px, rgba(0,230,57,0.1) 1px, transparent 1px, transparent 3px)',
        grid: 'linear-gradient(rgba(0,230,57,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(0,230,57,0.06) 1px, transparent 1px)',
      },
      backgroundSize: {
        grid: '32px 32px',
      },
      keyframes: {
        flapOpen: {
          '0%': { transform: 'rotateX(0deg)' },
          '100%': { transform: 'rotateX(-180deg)' },
        },
        letterOut: {
          '0%': { transform: 'translateY(0%)', opacity: '1' },
          '70%': { transform: 'translateY(-90%)', opacity: '1' },
          '100%': { transform: 'translateY(-90%)', opacity: '0' },
        },
        sealCrack: {
          '0%': { transform: 'scale(1) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'scale(1.6) rotate(15deg)', opacity: '0' },
        },
        stampDrop: {
          '0%': { transform: 'scale(2.4)', opacity: '0' },
          '60%': { transform: 'scale(0.9)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        blink: {
          '0%, 45%': { opacity: '1' },
          '50%, 100%': { opacity: '0' },
        },
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        radarSweep: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        glitchShift: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '20%': { transform: 'translate(-2px, 1px)' },
          '40%': { transform: 'translate(2px, -1px)' },
          '60%': { transform: 'translate(-1px, -1px)' },
          '80%': { transform: 'translate(1px, 1px)' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        flicker: {
          '0%, 100%': { opacity: '1' },
          '92%': { opacity: '1' },
          '93%': { opacity: '0.4' },
          '94%': { opacity: '1' },
          '96%': { opacity: '0.6' },
          '97%': { opacity: '1' },
        },
      },
      animation: {
        'flap-open': 'flapOpen 0.6s ease-in forwards',
        'letter-out': 'letterOut 1.1s ease-out forwards',
        'seal-crack': 'sealCrack 0.4s ease-out forwards',
        'stamp-drop': 'stampDrop 0.5s cubic-bezier(.36,1.5,.5,1) forwards',
        blink: 'blink 1s steps(1) infinite',
        marquee: 'marquee 22s linear infinite',
        radar: 'radarSweep 4s linear infinite',
        glitch: 'glitchShift 0.3s steps(2) infinite',
        'shake-once': 'glitchShift 0.4s steps(2) 2',
        'fade-up': 'fadeUp 0.6s ease-out forwards',
        flicker: 'flicker 6s linear infinite',
      },
    },
  },
  plugins: [],
}
